### PR TITLE
Added some stuff

### PR DESCRIPTION
**Pull request by cnnrde**
Added a really cool button https://kaboom.dev

### CODE REVIEW

**Comment by piemadd** [comment]
poop

**Comment by cnnrde** [comment]
poop

**Comment by piemadd** [comment]
pee

**Comment by cnnrde** [comment]
turds

**Comment by piemadd** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by cnnrde** [comment]
bbbbbbbbbbbbbbbbbbbbbbbbbbbb

**Pull request closed without merging**
